import { StyleSheet, Dimensions,Platform } from 'react-native';
import { scaleHeight, scaleWidth, normalizeFont } from '../../Constants/dynamicSize';
import { COLORS } from '../../Constants/Colors';
import { FONTS } from '../../Constants/Fonts';
const { width, height } = Dimensions.get('window');
export const styles = StyleSheet.create({
    floating_button: {
        backgroundColor: COLORS.WHITE,
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        height: 45,
        width: 45,
        borderRadius: 50,
        borderColor: COLORS.NEW_HEADER,
        borderWidth: 3,
        top: Platform.OS === 'ios' ? '80%' : '70%',
        left: '80%',
    },
    shadowbox: {
        height: 225,
        position: 'absolute',
        alignSelf: 'center',
        width: scaleWidth(350),
    },
    chartheader: {
        textAlign: 'left',
        color: 'grey',
        fontWeight: '500',
        marginTop: scaleHeight(25),
        fontFamily: FONTS.SEGOEUIBOLD,
    },
    titlebox: {
        backgroundColor: COLORS.HEADERBG,
        width: '100%',
        height: scaleHeight(48),
        alignItems: 'center',
        justifyContent: 'center',
    },
    charttitle: {
        textAlign: 'left',
        fontSize: normalizeFont(14),
        fontWeight: '800',
        color: COLORS.GREEN1,
        marginLeft: scaleWidth(10),
        fontFamily: FONTS.SEGOEUISEMIBOLD,
        marginVertical: scaleHeight(10),
    },
    buttontitle: {
        textAlign: 'center',
        width: '95%',
        fontSize: normalizeFont(18),
        fontWeight: 'bold',
        color: COLORS.WHITE,
        fontFamily: FONTS.SEGOEUISEMIBOLD,
    },
    aiimagetitle: {
        textAlign: 'left',
        width: '95%',
        fontSize: normalizeFont(22),
        fontWeight: 'bold',
        color: COLORS.BLACK,
        marginLeft: scaleWidth(10),
        fontFamily: FONTS.SEGOEUISEMIBOLD,
        marginVertical: scaleHeight(10),
    },
    button: {
        backgroundColor: COLORS.CHAT_BLUE,
        alignSelf: 'center',
        paddingVertical: 12,
        paddingHorizontal: 30,
        marginVertical: 10,
        borderRadius: 5,
        alignItems: 'center',
        width: '90%',
    },
    headerbox: {
        backgroundColor: COLORS.WHITE,
        shadowColor: Platform.OS === 'ios' ? '#fff' : '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 10,
        borderColor: '#D3D3D3',
        width: '100%',
        alignSelf: 'center',
    },
    divider: {
        height: scaleHeight(3),
        backgroundColor: COLORS.HEADERBG,
        marginTop: scaleHeight(10),
    },
    box: {
        backgroundColor: '#fff',
        width: '93%',
        alignSelf: 'center',
    },
    newbox: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    bot: {
        height: 35,
        width: 35,
    },
    floatingButton: {
        backgroundColor: COLORS.WHITE,
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        height: 45,
        width: 45,
        borderRadius: 50,
        borderColor: COLORS.NEW_HEADER,
        borderWidth: 3,
        top: Platform.OS === 'ios' ? '80%' : '70%',
        left: '80%'
    },
    modalbox: {
        position: 'absolute',
        backgroundColor: COLORS.WHITE,
        right: scaleWidth(40),
        bottom: Platform.OS === 'ios' ? 0 : 5,
        borderColor: COLORS.BLUE_BG,
        borderWidth: 1,
    },
    background_image: {
        width: scaleWidth(280),
        overflow: 'hidden',
    },
    container1: {
        alignItems: 'center',
        justifyContent: 'center',
        alignContent: 'center',
    },
    weather_container: {
        backgroundColor: COLORS.WHITE,
        width: scaleWidth(250),
        height: 100,
    },
    table_container: {
        padding: 10,
        backgroundColor: '#fff',
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderColor: '#ccc',
        paddingVertical: 10,
    },
    close: {
        height: scaleHeight(20),
        width: scaleWidth(20),
        tintColor: COLORS.WHITE,
    },
    event_text: {
        fontWeight: 'bold',
        color: COLORS.WHITE,
        marginVertical: scaleHeight(10),
        marginLeft: scaleWidth(40),
        width: scaleWidth(250),
        textAlign: 'center',
    },
    insight_view: {
        backgroundColor: COLORS.BLUE_NEW,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    insights: {
        fontWeight: 'bold',
        marginVertical: scaleHeight(10),
        color: COLORS.WHITE,
        marginLeft: scaleWidth(20),
        fontSize: normalizeFont(14),
    },
    closeview: {
        height: scaleHeight(40),
        width: scaleWidth(40),
        alignItems: 'center',
        justifyContent: 'center',
    },
    cell_text: {
        fontWeight: 'bold',
        left: 10,
        color: COLORS.BLACK,
        fontFamily: FONTS.SEGOEUISEMIBOLD,
    },
    container: {
        backgroundColor: COLORS.WHITE,
        width: 200,
    },
    containere: {
        width: 100,
        height: 50,
        overflow: 'hidden',
        flex: 1,
    },
    loading: {
        alignContent: 'center',
        justifyContent: 'center',
    },
    chart_container: {
        flex: 1,
    },
    plotly: {
        width: '100%',
        height: 50,
        flex: 1,
    },
    head: {
        height: 40,
        backgroundColor: '#f1f8ff',
    },
    text: {
        margin: 6,
    },
    wrapper: {
        flexDirection: 'row',
    },
    cell: {},
    border: {
        borderWidth: 1,
        borderColor: '#c8e1ff',
    },
    modal_container: {
        backgroundColor: 'transparent',
    },
    modal_background: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    circle_layer: {
        circleRadiusTransition: { duration: 5000, delay: 0 },
        circleColor: COLORS.HEADER,
    },
    bookmodal_view: {
        backgroundColor: COLORS.WHITE,
        alignSelf: 'center',
        shadowColor: Platform.OS === 'ios' ? '#fff' : COLORS.BLACKK,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 1,
        borderColor: COLORS.GREY,
        borderWidth: 0.1,
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        elevation: 5,
        overflow: 'hidden',
        height: height / 1.45,
    },
    modal_view: {
        backgroundColor: COLORS.NEW_HEADER,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
    },
});